### ISSUE TITLE
Purpose: Enhance Binding Performance

### ISSUE THREAD

**Issue by EP012014** [Paving-Base/APK-Installer#4]
UWP has a default boolean to visibility converter so you can directly bind boolean values to visibility.
Also, x:Bind provides a better performance than Binding.
For example, you can use "x:Bind AppSignatureInfoText.Text" here.
![image](https://user-images.githubusercontent.com/67152455/138550626-f0b18b41-aa2d-448d-8f4d-949c36237e15.png)

**Comment by wherewhere** [comment]
I use binding because I can simple copy it everywhere. Using xbind I need to change the name.<img alt="幽灵" src="https://raw.githubusercontent.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />
